[package]
name = "pcd-parser"
version.workspace = true
edition = "2021"

[dependencies]
csv = "1.3.0"
las = { version = "0.9.1", features = ["laz-parallel"] }
pcd-core = { path = "../pcd-core" }
projection-transform = {path = "../projection-transform"}
rayon = "1.10.0"
thiserror = "2.0"

[dev-dependencies]
